### ISSUE TITLE
error lua on CMAKE commande

### ISSUE THREAD

**Issue by grimgort** [Shatur/neovim-cmake#1]
Hello.

I have an error lua on cmake command 👍 
![image](https://user-images.githubusercontent.com/44238325/123990105-c6174600-d9c9-11eb-982b-75808964f7fe.png)

**Comment by Shatur** [comment]
Hi! You should install https://github.com/mfussenegger/nvim-dap.

**Comment by Shatur** [comment]
I assume that the issue can be closed.
