### ISSUE TITLE
Run does not recognize root path

### ISSUE THREAD

**Issue by chriztheanvill** [Shatur/neovim-cmake#15]
**Bug description**

Using :Cmake run or :CMake Build_and_run does not recognize the root path. Because my assets are in the rootpath. But if I made this "./build/linux-debug/bin/program_name it works excellent.

**Steps to reproduce**
:Cmake run or :CMake Build_and_run

Just installed the plugin.

**Expected behavior**

Run the program, loading the rootpath.

**Screenshots**

**Environment**

- OS: Kubuntu 21.10
- Desktop environment: KDE plasma 5
- Plugins commit hash: 

**Additional context**

For this, its the only problem, but if it could be change the settings:
* Telescope cmake select_target
* Telescope cmake select_build_type
This settings could be also available in :CMake menu? Like :CMake select_target

**Comment by Shatur** [comment]
> I made it, with

Great. Yes, this is how it usually done.
