### ISSUE TITLE
CMake build_and_run command runs old binaries

### ISSUE THREAD

**Issue by shrkamat** [Shatur/neovim-cmake#19]
Firstly thanks for this wonderful plugin

**Bug description**
`CMake build_and_run` command runs old binary upon build break.
Further build error goes unnoticed to developers.

**Steps to reproduce**
```
:Telescope cmake create_project
:CMake configure
:Telescope cmake select_target
:CMake buid_and_run

// now introduce a compile time error 
:CMake build_and_run

This run old binary
```

**Expected behavior**
* If build breaks, compile error logs should be shown & target binary shouldn't be run. 

**Screenshots**
[asciinema](https://asciinema.org/a/459906)

**Environment**

- OS:  Ubuntu 
- Desktop environment: Gnome 
- Plugins commit hash: 

**Additional context**
I understand `CMake build` and `CMake run` commands exists, but in my case `build_and_run` was a bit misleading to me.

**Comment by Shatur** [comment]
Oops, made a typo, thanks!
