### ISSUE TITLE
g:cmake_target_asyncrun_options ignores 'cwd' option

### ISSUE THREAD

**Issue by degmuk** [Shatur/neovim-cmake#2]
**Bug description**
Setting 'cwd' option in g:cmake_target_asyncrun_options has no effect (it always cd into executable's directory).

**Configuration**
```let g:cmake_target_asyncrun_options = {'cwd' : '<root>'}```

**Steps to reproduce**
1. Save some a.txt file
2. Run program opening ./a.txt file
3. See program fails

**Possible fix**
Changing line 49 in init.lua to this
```vim.fn['asyncrun#run']('', vim.fn.extend({ cwd = target_dir }, vim.g.cmake_target_asyncrun_options), command)```
fixed the issue.

**Comment by Shatur** [comment]
Thanks, fixed!
