### ISSUE TITLE
No output after CMake Run

### ISSUE THREAD

**Issue by zirco740** [Shatur/neovim-cmake#22]
**Bug description**
A blank terminal appears after using CMake run and I could type nothing in that terminal

**Steps to reproduce**

<details><summary>Minimal configuration</summary>
</details>

1. After building a c++ program
2. Run CMake run
3. Unexpected blank terminal is popped up
**Expected behavior**

There would be lines of output of my program.
**Screenshots**

![image](https://user-images.githubusercontent.com/54179931/150996647-5ae35c8c-fce5-4f39-b881-619b38598bee.png)

**Environment**

- OS:  Windows
- Desktop environment:  N/A
- Plugins commit hash: 

**Additional context**

**Comment by Shatur** [comment]
> Unexpected blank terminal is popped up

It's not a terminal. It's a quickfix output. I don't know why it's always blank in your case. Have you tried to wait to see if output appears? It's not empty on my Windows machine.

**Comment by zirco740** [comment]
> > Unexpected blank terminal is popped up
> 
> It's not a terminal. It's a quickfix output. I don't know why it's always blank in your case. Have you tried to wait to see if output appears? It's not empty on my Windows machine.

Yes, I have tried to wait, but nothing will appear in the quickfix output. When I try to click it or type something at it, it said that its not modifiable.

**Comment by Shatur** [comment]
> When I try to click it or type something at it, it said that its not modifiable.

It's because it's a quickfix. See `:h quickfix`. But I have no idea why it's empty.
