### ISSUE TITLE
execute command :CMake run, report err

### ISSUE THREAD

**Issue by xiaoLeeFeiDao** [Shatur/neovim-cmake#29]
**Describe the problem or limitation you are having**

When I run or debug, I get an error:
![图片](https://user-images.githubusercontent.com/97346214/158929411-64f02aaa-aee3-4868-ae2a-6b414fe001ae.png)

**Describe the solution you'd like**

1. When executing cmake run or debug, everything is normal and the result of the target operation is displayed
2. When CMakeLists.txt changes, reload cmake build config.. just like vscode
3. How to add the cmake command to the leadermap of lunarvim
**Describe alternatives you've considered**

NA
**Additional context**

**Comment by xiaoLeeFeiDao** [comment]
> 3\. How to add the cmake command to the leadermap of lunarvim

i'm so sorry!! this item has been resolved.

**Comment by Shatur** [comment]
> When I run or debug, I get an error:

You probably want to run `build_and_run` or `build_and_debug`.

> When CMakeLists.txt changes, reload cmake build config.. just like vscode

I don't like it. Configuration is run automatically if you change `CMakeLists.txt` and build the project. If you want to configure to update list of targets - just run configuration manually.
