### ISSUE TITLE
Pass build_args while executing build_all command

### ISSUE THREAD

**Issue by ravenxrz** [Shatur/neovim-cmake#31]
**Describe the problem or limitation you are having**

Pass `build_args` params while executing build_all command. 

**Describe the solution you'd like**

modify `cmake.build_all` function

**Comment by Shatur** [comment]
You already can pass additional cmake arguments when execution any of `CMake ...` command.

**Comment by ravenxrz** [comment]
I  pass a `-j`  argument almost every time when I  want to build some targets. So I will appreciate it if we can apply `build_args` opts while executing `CMake build_all`.

**Comment by Shatur** [comment]
Oh, to the `--build` command. But you can just set `MAKEFLAGS` environment variable.

**Comment by ravenxrz** [comment]
Ok, thanks, I will close this issuse.
