### ISSUE TITLE
Position of the quickfix window

### ISSUE THREAD

**Issue by Perry3D** [Shatur/neovim-cmake#36]
**Describe the problem or limitation you are having**
If I open the quickfix window manually i can do something like `:top copen` to specify the position of the window.

**Describe the solution you'd like**
A configuration option to specify the position of the quickfix window.
Maybe something like this:

```lua
require('cmake').setup({
  quickfix_pos = 'top'
})
```

**Comment by Shatur** [comment]
Agree, but since we also have `quickfix_height` and `quickfix_only_on_error`, I think we should introduce `quickfix` option and and put other quickfix-related parameters into it:

```lua
require('cmake').setup({
  quickfix = {
    pos = 'buttom',
    height = 10,
    only_on_error = false,
  }
})
```

**Comment by yucongxing** [comment]
> Agree, but since we also have `quickfix_height` and `quickfix_only_on_error`, I think we should introduce `quickfix` option and and put other quickfix-related parameters into it:
> 
> ```lua
> require('cmake').setup({
>   quickfix = {
>     pos = 'buttom',
>     height = 10,
>     only_on_error = false,
>   }
> })
> ```

how about "auto focus on the quickfix window", i cant find the configure now.

**Comment by yucongxing** [comment]
> 
thanks for your reply!
there are some reasons for my suggestion.
firstly, it inconvenient to close the quickfix window after run CMake commands. i need to navigate to it and closed.
secondly, i see the future feature(https://github.com/Shatur/neovim-cmake/issues/35#) about interact with the quickfix window (maybe a built-in terminal), if the feature is implemented, "auto focus" may become a needed configure.

**Comment by yucongxing** [comment]
> > how about "auto focus on the quickfix window", i cant find the configure now.
> 
> I don't see any use case for it. You can navigate quickfix items using `:qnext` or use awesome `vim-unimpaired`.

thanks for your reply!
there are some reasons for my suggestion.
firstly, it inconvenient to close the quickfix window after run CMake commands. i need to navigate to it and closed.
secondly, i see the future feature(https://github.com/Shatur/neovim-cmake/pull/35) about interact with the quickfix window (maybe a built-in terminal), if the feature is implemented, "auto focus" may become a needed configure.
