### ISSUE TITLE
Allow configuraltion of build arguments

### ISSUE THREAD

**Issue by csy19960309** [Shatur/neovim-cmake#5]
**Describe the problem or limitation you are having**
The compiling is slow and I want it to speed up.

**Describe the solution you'd like**
Make it possible to add build arguments such as "-j8" when building.

**Describe alternatives you've considered**
Use vscode-CMakeTools instead.

**Additional context**
None.

**Comment by Shatur** [comment]
I'll add configuration for the build arguments, but for now you can use the `MAKEFLAGS` environment variable as I do.

**Comment by csy19960309** [comment]
> I'll add configuration for the build arguments, but for now you can use the `MAKEFLAGS` environment variable as I do.

Thanks for the work.
