### ISSUE TITLE
Allow users to customize dap configurations

### ISSUE THREAD

**Issue by spindensity** [Shatur/neovim-cmake#6]
**Describe the problem or limitation you are having**

The dap configurations are hardcoded:
https://github.com/Shatur/neovim-cmake/blob/2b37c4a1b3374d9eef943aaeee6882d97675b6e6/lua/cmake/init.lua#L74-L83

The hard-coded configurations could not deal with adapters with server type which need `host` and `port` properties, such as `CodeLLDB`, see https://github.com/mfussenegger/nvim-dap/issues/307#issuecomment-927100276. If you use  adapters with server type,  an error would be raised:

![Snipaste_2021-09-30_13-19-39](https://user-images.githubusercontent.com/33576822/135391881-9cf9b648-a5d3-48c2-a6df-9e49dc4b67a2.png)

**Describe the solution you'd like**

Allow users to customize dap configurations

**Comment by Shatur** [comment]
Totally agree, will add configuration for this after work. Or you can speedup the process by sending a PR for it :)

**Comment by spindensity** [comment]
> Totally agree, will add configuration for this after work. Or you can speedup the process by sending a PR for it :)

OK, I'll send a PR.

**Comment by spindensity** [comment]
Done.
